### ISSUE TITLE
Help me to crack Geetest

### ISSUE THREAD

**Issue by hieplpvip** [wsguest/geetest#3]
I have read issue "Always returning "fail" #2" but I cannot understand it. I know a site similar to solebtc.com, it's autodoge.com. I think it's based on the same code. So @wsguest do you know the trick to bypass geetest. Here is some login information: baohiep1@extremail.ru.
Thank you very much if you could help me!

**Comment by cshunsinger** [comment]
So yeah. Basically with the one I bot, you can get the Geetest information without using a browser element. Instead you just use a few simple httpwebrequests.

So first you need to log in by doing the following:
1) Create a JSON object. I like using the ServiceStack.Text JsonObject from NuGet.
2) That json object will have one element named "email". It will contain the email of the account
3) Create an httpwebrequest to https://solebtc.com/api/v1/auth_tokens
3.5) The above step is for the faucet I use. It will probably be the same for autodoge, but with the autodoge domain. To find out for sure, do F12 and make sure you are in the networking tab. Then log in like normal and see what the request looks like.
4) Pack the text of your json object into the web request, and send the web request. Assuming you did it correctly, you should receive a JSON object containing the auth token. The auth token is sent as a header named "Auth-Token" every time you send another request to SoleBTC (which most likely means the same thing with Autodoge).
5) Once logged in (you have the auth token), simply send a request to https://solebtc.com/api/v1/users containing the auth token as a header. Once again, it is probably the same with autodoge, but may be different, and of course use the autodoge domain, not solebtc.
That request will return a JSON object with many elements, once of which details the last time an award was claimed so you know where you left off.
6) Once it is time to claim an award, you must first get the geetest information. Aka you need the challenge token and the gt token. So you just send an Http GET request to https://solebtc.com/api/v1/captchas. You actually don't have to include the auth token here, but what you will RECEIVE from the server is a json object containing a gt and a challenge key. You can plug those values into this library to solve the Geetest.
7) However, you will need to modify this library slightly. You will need a constructor that can take the gt and challenge keys rather than the GT and website. You will then need to have that constructor make a call to the RefreshGeetest function. I'm pretty sure the library will take care of the rest as far as solving the Geetest (when you call the validate function anyways).
8) If you pass the Geetest, then you will receive a JSON object with the validation token. You must submit that as a http POST request. This is to https://solebtc.com/api/v1/incomes/rewards. Send the validation key as a header named "X-Geetest-Validate", the Seccode as "X-Geetest-Seccode" (the seccode is just the validation token with the string "|jordan" pinned on the end). You must also send the challenge token as "X-Geetest-Challenge". However, you don't send the original challenge token. You send the challenge token you received after refreshing the Geetest using this library. Oh, and you must send your account's auth token as "Auth-Token".

**Comment by hieplpvip** [comment]
Thank you for replying me. I'll be very grateful if you send me the sample source code. My email is baohiep2013@gmail.com. I'm not an expert on C#.

**Comment by wsguest** [comment]
About earning coins, I know less than @TF2274 , and it appears that he has given a sufficiently detailed answer.

**Comment by cshunsinger** [comment]
I've actually run into a new problem with the api.
I have verified that the image unscrambler and edge detection is working, but for some reason every time I submit the answer, I get the response "forbidden" or "abuse". Any clue as to why this might be?

**Comment by hieplpvip** [comment]
So did you successfully hack it before?

**Comment by cshunsinger** [comment]
I was successful for weeks. This is very recent. I wonder if they changed part of their algorithm. I've even tried sending my Http requests through a proxy in case I was IP banned.

The thing is, the algorithm is sending the correct position. The thing isn't telling me I failed. It is saying "abuse" or "forbidden" for some reason.

**Comment by hieplpvip** [comment]
Maybe I can test it. Could you send me your program?

**Comment by cshunsinger** [comment]
You won't come to any conclusions since you say you aren't skilled at C#.

One of two things have essentially happened. Either I had too many bots going at once and the Geetest servers have decided that I am sending too many requests and need to take a break, or the Geetest company changed their algorithm recently for the response and/or action strings. Therefore the method of encoding used by this library is now sending the wrong string.

IF it is due to the second reason, then I suspect the action string is to blame. Perhaps the encoding is wrong due to Geetest's encoding changing.

The "Forbidden" message is essentially when the real thing says "Wow. A monster eats the image." Meaning the response was correct, but something else was wrong. Some other check.

And actually I can conclude that this isn't an IP ban type of issue because using a web proxy in my bot didn't work, and I can pass the geetest manually.

**Comment by hieplpvip** [comment]
I'm not good at C# but I am skilled at VB.NET. Maybe I can convert C# to VB and try to research it. I think VB is similar to C# in some ways.

**Comment by cshunsinger** [comment]
Perhaps, but I first want to hear from the author of this library about the matter.

**Comment by hieplpvip** [comment]
Hope he find a way to solve the problem

**Comment by hieplpvip** [comment]
Do you use facebook?

**Comment by cshunsinger** [comment]
Ok so apparently the library code does work, but it is taking numerous failures before working. I mean, it's literally taking 20 or more tries in order for me to receive a "success" message. All the other tries do succeed as far as the accuracy of the answer, but that is why I get the "forbidden" message. The answer is right, but there is something else that the Geetest server isn't appreciating.

I am using the Thread.Sleep(passTime) line of code which is supposedly supposed to make the code more likely to work.

There is also the occasional failure in which this library does provide the wrong answer, in which case the Geetest server responds with "fail" rather than "forbidden". So I can say with certainty that the library is producing the correct answer.

Intuition says it's perhaps something to do with the encoding of the action string.

EDIT: Resuming botting but with more console output. It's definitely something like 1 in 20+ Geetests being passed, with the rest being "forbidden".

**Comment by hieplpvip** [comment]
Have you tried your code with autodoge?

**Comment by wsguest** [comment]
@TF2274 According to your feedback, I guess the server has a dynamic defense mechanism. 
If you frequently submit requests over a certain number of times (1000?), you (actions, IP or other identifiers?) may be included in a suspected queue by  the algorithm for some time (24 hours?), during this period your request is strict checked. In my tests after being banned, manually posting will fail in a high probability, too. 
One possible solution is that you store all successful requests with time, and submit them after hours.

**Comment by cshunsinger** [comment]
Well it is actually kind of odd. I added a proxy system where you load proxies and the bot reads the proxies and uses them on an as-needed basis. Each account gets a proxy, and when one account is no longer able to successfully make any httprequests then it requests the next proxy in the list. If no proxy exists then it just runs like it did before I added proxies.

Turns out, I started having more and more geetests go through no problem. What was even more odd is that immediately after I stopped using proxies (they were too unreliable and I'm not ready to pay for premium proxies) it worked without fail. So I suspect you are right. What I will simply need to do is get a few cheap paid proxies and bot some accounts on that. Plus that will likely reduce the chances of getting banned by a small amount.

**Comment by hieplpvip** [comment]
Congratulation! Could you share your code with me? I'll send you some dollars as a thank you

**Comment by hieplpvip** [comment]
@TF2274 I have done all steps untill 6. At step 7, as I'm not skilled at C# so I can't modify the library. I've also tried to convert it to VB.NET but all I get are errors everywhere. So can you tell me how to completely modify the library? Thanks very much

**Comment by hieplpvip** [comment]
Ok, I have successfully crack it. Thanks @TF2274 for helping me and @wsguest for the library you created.
